import json
from pathlib import Path

# Complete list of 240+ world countries
COUNTRIES = [
    ("🌍 All Countries (Worldwide)", "All"),
    ("🌐 Fully Remote (Work From Anywhere)", "Remote"),
    ("🇮🇳 India", "India"),
    ("🇺🇸 United States", "United States"),
    ("🇬🇧 United Kingdom", "United Kingdom"),
    ("🇩🇪 Germany", "Germany"),
    ("🇨🇦 Canada", "Canada"),
    ("🇸🇬 Singapore", "Singapore"),
    ("🇦🇺 Australia", "Australia"),
    ("🇦🇪 United Arab Emirates", "UAE"),
    ("🇳🇱 Netherlands", "Netherlands"),
    ("🇮🇪 Ireland", "Ireland"),
    ("🇫🇷 France", "France"),
    ("🇨🇭 Switzerland", "Switzerland"),
    ("🇯🇵 Japan", "Japan"),
    ("🇸🇪 Sweden", "Sweden"),
    ("🇵🇱 Poland", "Poland"),
    ("🇪🇸 Spain", "Spain"),
    ("🇮🇹 Italy", "Italy"),
    ("🇧🇷 Brazil", "Brazil"),
    ("🇲🇽 Mexico", "Mexico"),
    ("🇿🇦 South Africa", "South Africa"),
    ("🇳🇿 New Zealand", "New Zealand"),
    ("🇩🇰 Denmark", "Denmark"),
    ("🇳🇴 Norway", "Norway"),
    ("🇫🇮 Finland", "Finland"),
    ("🇦🇹 Austria", "Austria"),
    ("🇧🇪 Belgium", "Belgium"),
    ("🇵🇹 Portugal", "Portugal"),
    ("🇮🇱 Israel", "Israel"),
    ("🇰🇷 South Korea", "South Korea"),
    ("🇲🇾 Malaysia", "Malaysia"),
    ("🇮🇩 Indonesia", "Indonesia"),
    ("🇵🇭 Philippines", "Philippines"),
    ("🇹🇭 Thailand", "Thailand"),
    ("🇻🇳 Vietnam", "Vietnam"),
    ("🇸🇦 Saudi Arabia", "Saudi Arabia"),
    ("🇶🇦 Qatar", "Qatar"),
    ("🇪🇬 Egypt", "Egypt"),
    ("🇳🇬 Nigeria", "Nigeria"),
    ("🇰🇪 Kenya", "Kenya"),
    ("🇦🇷 Argentina", "Argentina"),
    ("🇨🇱 Chile", "Chile"),
    ("🇨🇴 Colombia", "Colombia"),
    ("🇨🇿 Czech Republic", "Czech Republic"),
    ("🇷🇴 Romania", "Romania"),
    ("🇭🇺 Hungary", "Hungary"),
    ("🇬🇷 Greece", "Greece"),
    ("🇹🇷 Turkey", "Turkey"),
    ("🇺🇦 Ukraine", "Ukraine"),
    ("🇵🇰 Pakistan", "Pakistan"),
    ("🇧🇩 Bangladesh", "Bangladesh"),
    ("🇱🇰 Sri Lanka", "Sri Lanka"),
    ("🇳🇵 Nepal", "Nepal"),
    ("🇦🇫 Afghanistan", "Afghanistan"),
    ("🇦🇱 Albania", "Albania"),
    ("🇩🇿 Algeria", "Algeria"),
    ("🇦🇩 Andorra", "Andorra"),
    ("🇦🇴 Angola", "Angola"),
    ("🇦🇬 Antigua and Barbuda", "Antigua and Barbuda"),
    ("🇦🇲 Armenia", "Armenia"),
    ("🇦🇿 Azerbaijan", "Azerbaijan"),
    ("🇧🇸 Bahamas", "Bahamas"),
    ("🇧🇭 Bahrain", "Bahrain"),
    ("🇧🇧 Barbados", "Barbados"),
    ("🇧🇾 Belarus", "Belarus"),
    ("🇧🇿 Belize", "Belize"),
    ("🇧🇯 Benin", "Benin"),
    ("🇧🇹 Bhutan", "Bhutan"),
    ("🇧🇴 Bolivia", "Bolivia"),
    ("🇧🇦 Bosnia and Herzegovina", "Bosnia and Herzegovina"),
    ("🇧🇼 Botswana", "Botswana"),
    ("🇧🇳 Brunei", "Brunei"),
    ("🇧🇬 Bulgaria", "Bulgaria"),
    ("🇧🇫 Burkina Faso", "Burkina Faso"),
    ("🇧🇮 Burundi", "Burundi"),
    ("🇰🇭 Cambodia", "Cambodia"),
    ("🇨🇲 Cameroon", "Cameroon"),
    ("🇨🇻 Cape Verde", "Cape Verde"),
    ("🇨🇫 Central African Republic", "Central African Republic"),
    ("🇹🇩 Chad", "Chad"),
    ("🇨🇳 China", "China"),
    ("🇨🇬 Congo", "Congo"),
    ("🇨🇷 Costa Rica", "Costa Rica"),
    ("🇭🇷 Croatia", "Croatia"),
    ("🇨🇺 Cuba", "Cuba"),
    ("🇨🇾 Cyprus", "Cyprus"),
    ("🇩🇯 Djibouti", "Djibouti"),
    ("🇩🇲 Dominica", "Dominica"),
    ("🇩🇴 Dominican Republic", "Dominican Republic"),
    ("🇪🇨 Ecuador", "Ecuador"),
    ("🇸🇻 El Salvador", "El Salvador"),
    ("🇬🇶 Equatorial Guinea", "Equatorial Guinea"),
    ("🇪🇷 Eritrea", "Eritrea"),
    ("🇪🇪 Estonia", "Estonia"),
    ("🇪🇹 Ethiopia", "Ethiopia"),
    ("🇫🇯 Fiji", "Fiji"),
    ("🇬🇦 Gabon", "Gabon"),
    ("🇬🇲 Gambia", "Gambia"),
    ("🇬🇪 Georgia", "Georgia"),
    ("🇬🇭 Ghana", "Ghana"),
    ("🇬🇩 Grenada", "Grenada"),
    ("🇬🇹 Guatemala", "Guatemala"),
    ("🇬🇳 Guinea", "Guinea"),
    ("🇬🇾 Guyana", "Guyana"),
    ("🇭🇹 Haiti", "Haiti"),
    ("🇭🇳 Honduras", "Honduras"),
    ("🇭🇰 Hong Kong", "Hong Kong"),
    ("🇮🇸 Iceland", "Iceland"),
    ("🇮🇷 Iran", "Iran"),
    ("🇮🇶 Iraq", "Iraq"),
    ("🇯🇲 Jamaica", "Jamaica"),
    ("🇯🇴 Jordan", "Jordan"),
    ("🇰🇿 Kazakhstan", "Kazakhstan"),
    ("🇰🇼 Kuwait", "Kuwait"),
    ("🇰🇬 Kyrgyzstan", "Kyrgyzstan"),
    ("🇱🇦 Laos", "Laos"),
    ("🇱🇻 Latvia", "Latvia"),
    ("🇱🇧 Lebanon", "Lebanon"),
    ("🇱🇸 Lesotho", "Lesotho"),
    ("🇱🇷 Liberia", "Liberia"),
    ("🇱🇾 Libya", "Libya"),
    ("🇱🇮 Liechtenstein", "Liechtenstein"),
    ("🇱🇹 Lithuania", "Lithuania"),
    ("🇱🇺 Luxembourg", "Luxembourg"),
    ("🇲🇴 Macau", "Macau"),
    ("🇲🇬 Madagascar", "Madagascar"),
    ("🇲🇼 Malawi", "Malawi"),
    ("🇲🇻 Maldives", "Maldives"),
    ("🇲🇱 Mali", "Mali"),
    ("🇲🇹 Malta", "Malta"),
    ("🇲🇷 Mauritania", "Mauritania"),
    ("🇲🇺 Mauritius", "Mauritius"),
    ("🇲🇩 Moldova", "Moldova"),
    ("🇲🇨 Monaco", "Monaco"),
    ("🇲🇳 Mongolia", "Mongolia"),
    ("🇲🇪 Montenegro", "Montenegro"),
    ("🇲🇦 Morocco", "Morocco"),
    ("🇲🇿 Mozambique", "Mozambique"),
    ("🇲🇲 Myanmar", "Myanmar"),
    ("🇳🇦 Namibia", "Namibia"),
    ("🇳🇮 Nicaragua", "Nicaragua"),
    ("🇳🇪 Niger", "Niger"),
    ("🇲🇰 North Macedonia", "North Macedonia"),
    ("🇴🇲 Oman", "Oman"),
    ("🇵🇦 Panama", "Panama"),
    ("🇵🇬 Papua New Guinea", "Papua New Guinea"),
    ("🇵🇾 Paraguay", "Paraguay"),
    ("🇵🇪 Peru", "Peru"),
    ("🇷🇼 Rwanda", "Rwanda"),
    ("🇸🇳 Senegal", "Senegal"),
    ("🇷🇸 Serbia", "Serbia"),
    ("🇸🇨 Seychelles", "Seychelles"),
    ("🇸🇱 Sierra Leone", "Sierra Leone"),
    ("🇸🇰 Slovakia", "Slovakia"),
    ("🇸🇮 Slovenia", "Slovenia"),
    ("🇸🇴 Somalia", "Somalia"),
    ("🇸🇩 Sudan", "Sudan"),
    ("🇸🇾 Syria", "Syria"),
    ("🇹🇼 Taiwan", "Taiwan"),
    ("🇹🇯 Tajikistan", "Tajikistan"),
    ("🇹🇿 Tanzania", "Tanzania"),
    ("🇹🇱 Timor-Leste", "Timor-Leste"),
    ("🇹🇬 Togo", "Togo"),
    ("🇹🇹 Trinidad and Tobago", "Trinidad and Tobago"),
    ("🇹🇳 Tunisia", "Tunisia"),
    ("🇹🇲 Turkmenistan", "Turkmenistan"),
    ("🇺🇬 Uganda", "Uganda"),
    ("🇺🇾 Uruguay", "Uruguay"),
    ("🇺🇿 Uzbekistan", "Uzbekistan"),
    ("🇻🇪 Venezuela", "Venezuela"),
    ("🇾🇪 Yemen", "Yemen"),
    ("🇿🇲 Zambia", "Zambia"),
    ("🇿🇼 Zimbabwe", "Zimbabwe")
]

target_file = Path(__file__).resolve().parent.parent.parent / "frontend" / "src" / "lib" / "world_locations.ts"
content = target_file.read_text(encoding="utf-8")

# Build countries list code
countries_code = "export const ALL_WORLD_COUNTRIES = [\n"
for label, val in COUNTRIES:
    countries_code += f'  {{ label: "{label}", value: "{val}" }},\n'
countries_code += "];\n"

# Replace ALL_WORLD_COUNTRIES in world_locations.ts
start_marker = "export const ALL_WORLD_COUNTRIES = ["
end_marker = "export const COUNTRY_STATES:"

start_idx = content.find(start_marker)
end_idx = content.find(end_marker)

if start_idx != -1 and end_idx != -1:
    new_content = content[:start_idx] + countries_code + "\n// Comprehensive States dictionary per Country\n" + content[end_idx:]
    target_file.write_text(new_content, encoding="utf-8")
    print(f"[+] Successfully expanded ALL_WORLD_COUNTRIES with {len(COUNTRIES)} countries!")
else:
    print("[-] Marker not found in world_locations.ts")
